{
    buy = {
        coords = {text = 3, count = 34, cost = 50},

        {text="Железный слиток",cost=10,fingerprint={{dmg=0.0,id="minecraft:iron_ingot"}}},
        {text="Золотой слиток",cost=15,fingerprint={{dmg=0.0,id="minecraft:gold_ingot"}}},
        {text="Медный слиток",cost=10,fingerprint={{dmg=0.0,id="IC2:itemIngot"},{dmg=64.0,id="ThermalFoundation:material"}}},
        {text="Оловянный слиток",cost=10,fingerprint={{dmg=6.0,id="Mekanism:Ingot"},{dmg=65.0,id="ThermalFoundation:material"},{dmg=1.0,id="IC2:itemIngot"}}},
        {text="Осмиевый слиток",cost=20,fingerprint={{dmg=1.0,id="Mekanism:Ingot"}}},
        {text="Серебряный",cost=15,fingerprint={{dmg=66.0,id="ThermalFoundation:material"},{dmg=6.0,id="IC2:itemIngot"}}},
        {text="Платиновый слиток",cost=70,fingerprint={{dmg=69.0,id="ThermalFoundation:material"}}},
        {text="Тритановый слиток",cost=15,fingerprint={{dmg=0.0,id="mo:tritanium_ingot"}}},
        {text="Алюминиевый слиток",cost=6,fingerprint={{dmg=1.0,id="ImmersiveEngineering:metal"}}},
        {text="Светопыль",cost=3,fingerprint={{dmg=0.0,id="minecraft:glowstone_dust"}}},
        {text="Красная пыль",cost=3,fingerprint={{dmg=0.0,id="minecraft:redstone"}}},
        {text="Костная мука",cost=3,fingerprint={{id="minecraft:dye",dmg=15.0}}},
        {text="Жемчуг эндера",cost=9,fingerprint={{id="minecraft:ender_pearl",dmg=0.0}}},
        {text="Алмаз",cost=150,fingerprint={{id="minecraft:diamond",dmg=0.0}}},
        {text="Изумруд",cost=135,fingerprint={{id="minecraft:emerald",dmg=0.0}}},
        {text="Лазурит",cost=6,fingerprint={{id="minecraft:dye",dmg=4.0}}},
        {text="Кварц",cost=15,fingerprint={{id="minecraft:quartz",dmg=0.0}}},
        {text="Стержень ифрита",cost=7,fingerprint={{id="minecraft:blaze_rod",dmg=0.0}}},
        {text="Дилитиевый кристалл",cost=45,fingerprint={{id="mo:dilithium_crystal",dmg=0.0}}},
        {text="Уголь",cost=4,fingerprint={{id="minecraft:coal",dmg=0.0}}},
        {text="Апатит",cost=5,fingerprint={{id="Forestry:apatite",dmg=0.0}}},

        {text="Красная пилюля",cost=200000,fingerprint={{id="mo:android_pill",dmg=0.0}}},
        {text="Сахарный тростник",cost=1,fingerprint={{id="minecraft:reeds",dmg=0.0}}},
        {text="Капсула хладагента",cost=200,fingerprint={{dmg=9.0,id="IC2:itemCellEmpty"}}},
        {text="Энергетический кристалл",cost=600,fingerprint={{dmg=27.0,id="IC2:itemBatCrystal"}}},
        {text="Прибор ночного видения",cost=1400,fingerprint={{dmg=26.0,id="IC2:itemNightvisionGoggles"}}},
        {text="Нано-кираса",cost=1500,fingerprint={{dmg=26.0,id="IC2:itemArmorNanoChestplate"}}},
        {text="Голова зомби",cost=150,fingerprint={{dmg=2.0,id="minecraft:skull"}}},
        {text="Иридий",cost=350,fingerprint={{dmg=0.0,id="IC2:itemOreIridium"}}},
        {text="Углепластик",cost=130,fingerprint={{dmg=0.0,id="IC2:itemPartCarbonPlate"}}},
        {text="Композит",cost=120,fingerprint={{dmg=0.0,id="IC2:itemPartAlloy"}}},
        {text="Нано-сабля",cost=1300,fingerprint={{dmg=26.0,id="IC2:itemNanoSaber"}}},
        {text="Токарная форма для бура",cost=190,fingerprint={{nbt_hash="6c8fa259d8230120db4ec331abff09c7",dmg=2930.0,id="IC2:itemTurningBlanks"}}},
        {text="Нано-ботинки",cost=1300,fingerprint={{dmg=26.0,id="IC2:itemArmorNanoBoots"}}},
        {text="Нано-поножи",cost=1400,fingerprint={{dmg=26.0,id="IC2:itemArmorNanoLegs"}}},
        {text="Нано-шлем",cost=1900,fingerprint={{dmg=26.0,id="IC2:itemArmorNanoHelmet"}}},
        {text="16К МЭ ячейка хранения",cost=6000,fingerprint={{dmg=0.0,id="appliedenergistics2:item.ItemBasicStorageCell.16k"}}},
        {text="Ускоритель",cost=600,fingerprint={{dmg=0.0,id="IC2:upgradeModule"}}},
        {text="Выч. пресс для высекателя",cost=350,fingerprint={{dmg=13.0,id="appliedenergistics2:item.ItemMultiMaterial"}}},
        {text="Инж. пресс для высекателя",cost=350,fingerprint={{dmg=14.0,id="appliedenergistics2:item.ItemMultiMaterial"}}},
        {text="Крем. пресс для высекателя",cost=350,fingerprint={{dmg=19.0,id="appliedenergistics2:item.ItemMultiMaterial"}}},
        {text="Лог. пресс для высекателя",cost=350,fingerprint={{dmg=15.0,id="appliedenergistics2:item.ItemMultiMaterial"}}},
        {text="Улучшенная солнечная панель",cost=5000,fingerprint={{dmg=0.0,id="AdvancedSolarPanel:BlockAdvSolarPanel"}}},
        {text="Фотовольтовая ячейка(10 EU/T)",cost=3500,fingerprint={{dmg=1.0,id="EnderIO:blockSolarPanel"}}},
        {text="Улучшенный наножилет",cost=25000,fingerprint={{dmg=26.0,id="GraviSuite:advNanoChestPlate"}}},
        {text="Квантовый шлем",cost=14000,fingerprint={{dmg=26.0,id="IC2:itemArmorQuantumHelmet"}}},
        {text="Квантовые поножи",cost=14000,fingerprint={{dmg=26.0,id="IC2:itemArmorQuantumLegs"}}},
        {text="Квантовые ботинки",cost=14000,fingerprint={{dmg=26.0,id="IC2:itemArmorQuantumBoots"}}},
        {text="Стальной слиток",cost=60,fingerprint={{dmg=4.0,id="Mekanism:Ingot"}}},
        {text="Улучшенный алмазный бур",cost=6000,fingerprint={{dmg=26.0,id="GraviSuite:advDDrill"}}},
        {text="Чистый кр. ист. кварца",cost=40,fingerprint={{dmg=10.0,id="appliedenergistics2:item.ItemMultiMaterial"}}},
        {text="Сгусток слизи",cost=35,fingerprint={{id="minecraft:slime_ball",dmg=0.0}}},
    },

    sell = {
        coords = {text = 3, cost = 38},

        {text="Кристалл истинного кварца",cost=40,raw_name={"item.appliedenergistics2.itemmaterial.certusquartzcrystal"}},
        {text="Железная руда",cost=30,raw_name={"tile.oreiron"}},
        {text="Золотая руда",cost=30,raw_name={"tile.oregold"}},
        {text="Медная руда",cost=30,raw_name={"tile.thermalfoundation.ore.copper.name","ic2.blockorecopper"}},
        {text="Оловянная руда",cost=20,raw_name={"tile.thermalfoundation.ore.tin.name","ic2.blockoretin"}},
        {text="Серебряная руда",cost=30,raw_name={"tile.thermalfoundation.ore.silver.name"}},
        {text="Платиновая руда",cost=70,raw_name={"tile.thermalfoundation.ore.platinum.name"}},
        {text="Тритановая руда",cost=30,raw_name={"tile.tritanium_ore"}},
        {text="Бокситовая руда",cost=30,raw_name={"tile.immersiveengineering.ore.aluminum"}},

        {text="Железный слиток",cost=5,raw_name={"item.ingotiron"}},
        {text="Золотой слиток",cost=5,raw_name={"item.ingotgold"}},
        {text="Медный слиток",cost=5,raw_name={"item.thermalfoundation.material.ingotcopper","ic2.itemingotcopper","item.immersiveengineering.metal.ingotcopper"}},
        {text="Оловянный слиток",cost=5,raw_name={"item.thermalfoundation.material.ingottin","ic2.itemingottin","item.tiningot"}},
        {text="Осмиевый слиток",cost=7,raw_name={"item.osmiumingot"}},
        {text="Серебряный слиток",cost=6,raw_name={"item.thermalfoundation.material.ingotsilver","ic2.itemingotsilver"}},
        {text="Платиновый слиток",cost=50,raw_name={"item.thermalfoundation.material.ingotplatinum"}},
        {text="Тритановый слиток",cost=6,raw_name={"item.tritanium_ingot"}},
        {text="Алюминиевый слиток",cost=5,raw_name={"item.immersiveengineering.metal.ingotaluminum"}},
        {text="Светопыль",cost=2,raw_name={"item.yellowdust"}},
        {text="Красная пыль",cost=1,raw_name={"item.redstone"}},
        {text="Костная мука",cost=0.1,raw_name={"item.dyepowder.white"}},
        {text="Жемчуг эндера",cost=4,raw_name={"item.enderpearl"}},
        {text="Алмаз",cost=80,raw_name={"item.diamond"}},
        {text="Изумруд",cost=95,raw_name={"item.emerald"}},
        {text="Лазурит",cost=3,raw_name={"item.dyepowder.blue"}},
        {text="Кварц",cost=4,raw_name={"item.netherquartz"}},
        {text="Стержень ифрита",cost=3,raw_name={"item.blazerod"}},
        {text="Дилитиевый кристалл",cost=7,raw_name={"item.dilithium_crystal"}},
        {text="Уголь",cost=2,raw_name={"item.coal"}},
        {text="Апатит",cost=2,raw_name={"item.for.apatite"}}
    },

    ore = {
        {text="Железная руда",ratio=2,raw_name={"tile.oreiron"},fingerprint={ore={{dmg=0.0,id="minecraft:iron_ore"}},ingot={{dmg=0.0,id="minecraft:iron_ingot"}}}},
        {text="Золотая руда",ratio=2,raw_name={"tile.oregold"},fingerprint={ore={{dmg=0.0, id="minecraft:gold_ingot"}},ingot={{dmg=0.0,id="minecraft:gold_ingot"}}}},
        {text="Медная руда",ratio=2,raw_name={"tile.thermalfoundation.ore.copper.name","ic2.blockorecopper"},fingerprint={ore={{dmg=0.0,id="ThermalFoundation:Ore"},{dmg=0.0,id="IC2:blockOreCopper"}},ingot={{dmg=64.0,id="ThermalFoundation:material"},{dmg=0.0,id="IC2:itemIngot"}}}},
        {text="Оловянная руда",ratio=2,raw_name={"tile.thermalfoundation.ore.tin.name","ic2.blockoretin"},fingerprint={ore={{dmg=1.0,id="ThermalFoundation:Ore"},{dmg=0.0,id="IC2:blockOreTin"}},ingot={{dmg=6.0,id="Mekanism:Ingot"},{dmg=65.0,id="ThermalFoundation:material"},{dmg=1.0,id="IC2:itemIngot"}}}},
        {text="Серебряная руда",ratio=2,raw_name={"tile.thermalfoundation.ore.silver.name"},fingerprint={ore={dmg=2.0,id="ThermalFoundation:Ore"},ingot={{dmg=66.0,id="ThermalFoundation:material"},{dmg=6.0,id="IC2:itemIngot"}}}},
        {text="Осмиевая руда",ratio=2,raw_name={"tile.oreblock.osmiumore"},fingerprint={ore={{dmg=0.0,id="Mekanism:OreBlock"}},ingot={{dmg=1.0,id="Mekanism:Ingot"}}}},
        {text="Свинцовая руда",ratio=2,raw_name={"tile.thermalfoundation.ore.lead.name","ic2.blockorelead"},fingerprint={ore={{dmg=3.0, id="ThermalFoundation:Ore"},{dmg=0.0,id="IC2:blockOreLead"}},ingot={{dmg=67.0,id="ThermalFoundation:material"},{dmg=5.0,id="IC2:itemIngot"}}}}
    },

    food = {{dmg=0.0, id="minecraft:melon"},{id="minecraft:apple",dmg=0.0}}
}
